export const CATALOG = [
  {
    id: 'el1',
    img: 'https://i.ibb.co/njPzjPD/11.jpg',
    name: 'Apple iPhone 11',
    quantity: 12,
    price: 200,
    releaseDate: 2018,
    popular: 'да',
    color: 'белый',
    numberOfCameras: 2,
    brand: 'Apple',
  },
  {
    id: 'el2',
    img: 'https://i.ibb.co/Qv869FZ/12.jpg',
    name: 'Apple iPhone 12',
    quantity: 2,
    price: 200,
    releaseDate: 2010,
    popular: 'нет',
    color: 'желтый',
    numberOfCameras: 3,
    brand: 'Apple',
  },
  {
    id: 'el3',
    img: 'https://i.ibb.co/Pw2bMqB/13.jpg',
    name: 'Apple iPhone 13',
    quantity: 10,
    price: 200,
    releaseDate: 2009,
    popular: 'нет',
    color: 'красный',
    numberOfCameras: 3,
    brand: 'Apple',
  },
  {
    id: 'el4',
    img: 'https://i.ibb.co/smnd3QM/se.jpg',
    name: 'Apple iPhone SE',
    quantity: 12,
    price: 200,
    releaseDate: 2004,
    popular: 'нет',
    color: 'белый',
    numberOfCameras: 1,
    brand: 'Apple',
  },

  {
    id: 'el5',
    img: 'https://i.ibb.co/2ZRPKFt/x4.jpg',
    name: ' Xiaomi Poco X4 pro',
    quantity: 1,
    price: 200,
    releaseDate: 2014,
    popular: 'нет',
    color: 'желтый',
    numberOfCameras: 2,
    brand: 'Xiaomi',
  },
  {
    id: 'el6',
    img: 'https://i.ibb.co/BB3ZFYn/9c.jpg',
    name: 'Xiaomi Redmi 9C 3 / 64gb',
    quantity: 6,
    price: 200,
    releaseDate: 2010,
    popular: 'нет',
    color: 'красный',
    numberOfCameras: 2,
    brand: 'Xiaomi',
  },
  {
    id: 'el7',
    img: 'https://i.ibb.co/1qxCkvQ/note11.jpg',
    name: 'Xiaomi Redmi Note 11',
    quantity: 4,
    price: 200,
    releaseDate: 2012,
    popular: 'да',
    color: 'белый',
    numberOfCameras: 1,
    brand: 'Xiaomi',
  }, {
    id: 'el8',
    img: 'https://i.ibb.co/Lv2Sfj1/A03.png',
    name: 'Samsung Galaxy A03',
    quantity: 5,
    price: 200,
    releaseDate: 2000,
    popular: 'нет',
    color: 'красный',
    numberOfCameras: 2,
    brand: 'Samsung',
  },
  {
    id: 'el9',
    img: 'https://i.ibb.co/SBC19nL/S20.jpg',
    name: 'Samsung Galaxy S20',
    quantity: 3,
    price: 200,
    releaseDate: 2022,
    popular: 'нет',
    color: 'желтый',
    numberOfCameras: 1,
    brand: 'Samsung',
  },
  {
    id: 'el10',
    img: 'https://i.ibb.co/nwvz5zV/S21.jpg',
    name: 'Samsung Galaxy S21',
    quantity: 2,
    price: 200,
    releaseDate: 2019,
    popular: 'нет',
    color: 'белый',
    numberOfCameras: 3,
    brand: 'Samsung',
  },

];
